spring:
  profiles: peer-0
server:
  port: 9020
eureka:
  instance:
    hostname: peer0-eureka-server.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1-eureka-server.com:9021/eureka/, http://peer2-eureka-server.com:9022/eureka/

---
spring:
  profiles: peer-1
server:
  port: 9021
eureka:
  instance:
    hostname: peer1-eureka-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer0-eureka-server.com:9020/eureka/, http://peer2-eureka-server.com:9022/eureka/

---
spring:
  profiles: peer-2
server:
  port: 9022
eureka:
  instance:
    hostname: peer2-eureka-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1-eureka-server.com:9021/eureka/, http://peer0-eureka-server.com:9020/eureka/