spring:
  application:
    name: spring-cloud-employee
  profiles: default
  cloud:
    config:
      uri: http://localhost:9000
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9020/eureka/
management:
  security:
    enabled: false
security:
  basic:
    enable: false
